project_id = "xeloigymjjeejvicadar"

[functions.google-calendar-worker]
verify_jwt = false

[functions.chatbot-luna-builder]
verify_jwt = false

[functions.prospect-analyzer]
verify_jwt = false

[functions.prospect-sender]
verify_jwt = false

[functions.global-message-generator]
verify_jwt = false
