project_id = "xeloigymjjeejvicadar"

[functions.google-calendar-worker]
verify_jwt = false

[functions.chatbot-luna-builder]
verify_jwt = false

[functions.prospect-analyzer]
verify_jwt = false

[functions.prospect-sender]
verify_jwt = false

[functions.global-message-generator]
verify_jwt = false

[functions.send-whatsapp-genesis]
verify_jwt = false

[functions.enrich-prospect]
verify_jwt = false

[functions.global-radar]
verify_jwt = false

[functions.send-petshop-whatsapp]
verify_jwt = false

[functions.luna-whatsapp-assistant]
verify_jwt = false

[functions.luna-setup-webhook]
verify_jwt = false
