project_id = "wvnszzrvrrueuycrpgyc"

[functions.create-admin-user]
verify_jwt = false

[functions.delete-admin-user]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true

[functions.setup-super-admin]
verify_jwt = false

[functions.webhook-trigger]
verify_jwt = false

[functions.send-real-push]
verify_jwt = false

[functions.appointments-api]
verify_jwt = false

[functions.send-chatpro]
verify_jwt = false

[functions.send-marketing]
verify_jwt = false

[functions.generate-marketing-prompt]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.confirm-email-token]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.send-welcome-whatsapp]
verify_jwt = false
