project_id = "wvnszzrvrrueuycrpgyc"

[functions.create-admin-user]
verify_jwt = false

[functions.delete-admin-user]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true

[functions.setup-super-admin]
verify_jwt = false

[functions.webhook-trigger]
verify_jwt = false

[functions.send-real-push]
verify_jwt = false